### ISSUE TITLE
com.hack_computer.Clubhouse is failed due to load glibcoro failed

### ISSUE THREAD

**Issue by starnight** [flathub/com.hack_computer.Clubhouse#22]
The current runs failed with the error:
```
$ flatpak run com.hack_computer.Clubhouse
Traceback (most recent call last):
  File "/app/bin/eos-clubhouse", line 62, in <module>
    _run_clubhouse()
  File "/app/bin/eos-clubhouse", line 36, in _run_clubhouse
    from eosclubhouse.clubhouse import ClubhouseApplication
  File "/app/lib/python3.10/site-packages/eosclubhouse/clubhouse.py", line 41, in <module>
  File "/app/lib/python3.10/site-packages/eosclubhouse/libquest.py", line 24, in <module>
ModuleNotFoundError: No module named 'glibcoro'
```

**Comment by starnight** [comment]
There is **glibcoro-0.5-py3.10.egg** in the flatpak app:
```
$ flatpak run --command=ls com.hack_computer.Clubhouse /app/lib/python3.10/site-packages/
eosclubhouse  glibcoro-0.5-py3.10.egg  persist_queue-0.5.0-py3.10.egg
```
Weird!?

**Comment by wjt** [comment]
I had a weird similar issue in the Dropbox Flatpak. I didn't really understand it but because I have a general dislike of `.egg`s I tried disabling the eggs. And that fixed it.

https://github.com/flathub/com.dropbox.Client/commit/6eeeac1309856894fe316678114950500845425b

**Comment by starnight** [comment]
Thanks @wjt    It does help!

Here is the modification candidate: 
```diff
diff --git a/com.hack_computer.Clubhouse.json b/com.hack_computer.Clubhouse.json
index c1cafee..9cb2721 100644
--- a/com.hack_computer.Clubhouse.json
+++ b/com.hack_computer.Clubhouse.json
@@ -188,7 +188,7 @@
                 }
             ],
             "build-commands": [
-                "python3 ./setup.py install --prefix=/app"
+                "python3 ./setup.py install --single-version-externally-managed --root / --prefix=/app"
             ]
         },
         {
@@ -203,7 +203,7 @@
                 }
             ],
             "build-commands": [
-                "python3 ./setup.py install --prefix=/app"
+                "python3 ./setup.py install --single-version-externally-managed --root / --prefix=/app"
             ]
         },
         {
```

However, following that, another warning during the runtime:
```
INFO:eosclubhouse:Running quest "Quickstart"
Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/glibcoro.py", line 93, in awaitit
    result = await future
  File "/app/lib/python3.10/site-packages/eosclubhouse/libquest.py", line 545, in wait_or_timeout
TypeError: wait() got an unexpected keyword argument 'loop'
Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/glibcoro.py", line 93, in awaitit
    result = await future
  File "/app/lib/python3.10/site-packages/eosclubhouse/libquest.py", line 545, in wait_or_timeout
TypeError: wait() got an unexpected keyword argument 'loop'
Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/glibcoro.py", line 93, in awaitit
    result = await future
  File "/app/lib/python3.10/site-packages/eosclubhouse/libquest.py", line 545, in wait_or_timeout
TypeError: wait() got an unexpected keyword argument 'loop'
```
We may need to update **glibcoro**, too.

**Comment by starnight** [comment]
> However, following that, another warning during the runtime:
> 
> ```
> INFO:eosclubhouse:Running quest "Quickstart"
> Traceback (most recent call last):
>   File "/app/lib/python3.10/site-packages/glibcoro.py", line 93, in awaitit
>     result = await future
>   File "/app/lib/python3.10/site-packages/eosclubhouse/libquest.py", line 545, in wait_or_timeout
> TypeError: wait() got an unexpected keyword argument 'loop'
> Traceback (most recent call last):
>   File "/app/lib/python3.10/site-packages/glibcoro.py", line 93, in awaitit
>     result = await future
>   File "/app/lib/python3.10/site-packages/eosclubhouse/libquest.py", line 545, in wait_or_timeout
> TypeError: wait() got an unexpected keyword argument 'loop'
> Traceback (most recent call last):
>   File "/app/lib/python3.10/site-packages/glibcoro.py", line 93, in awaitit
>     result = await future
>   File "/app/lib/python3.10/site-packages/eosclubhouse/libquest.py", line 545, in wait_or_timeout
> TypeError: wait() got an unexpected keyword argument 'loop'
> ```
I think this is another issue which does not happen directly.  It occurs with UI interaction.  So, prepare the fix first. https://github.com/flathub/com.hack_computer.Clubhouse/pull/23

**Comment by wjt** [comment]
See https://github.com/endlessm/clubhouse/commit/833e2f112952ba979008f627ab4bfd359d0f8cf2 for more information on the `loop` keyword argument.

**Comment by wjt** [comment]
https://github.com/endlessm/clubhouse/pull/1238#discussion_r725953342 also has discussion. It was known at the time that this would break in Python 3.10 :)

**Comment by wjt** [comment]
Resolved by downgrading the runtime to one with an older Python.
